### ISSUE TITLE
Feature Request: Update commands when settings are changed.

### ISSUE THREAD

**Issue by HaaLeo** [ryuta46/vscode-multi-command#1]
Currently when I add a command in the `settings.json` I need to restart vscode that the command will be registered and thus be available to use. 

## Feature Request
As user I do not want to restart vscode after I added a custom multi-command in the `settings.json`. I want to be able to use the command immediately after adding it to the `settings.json` and without restarting vscode.

## Implementation Suggestion
Configuration changes can be detected with the `vscode.workspace.onDidChangeConfiguration` event. So when this event hits update (deregister and register) all custom commands.

**Comment by ryuta46** [comment]
Thanks for your feature request and the implementation suggestion.
I'll try your suggestion.

**Comment by ryuta46** [comment]
@HaaLeo 

I implemented your feature request in v1.1.0.
Please try the new version, and report if you have any problem.

**Comment by HaaLeo** [comment]
Looks good to me :)

**Comment by ryuta46** [comment]
Thanks!
