### ISSUE TITLE
How do you find out what the commands are called in settings

### ISSUE THREAD

**Issue by AviCraimer** [ryuta46/vscode-multi-command#12]
Is there a way to check what a given command is called in the json settings notation. For example, if I open the command pallet I can see the natural language descriptions of commands e.g., "Python: Run Python File in Terminal" but this does not tell what that command would be called within the settings JSON, e.g., something like "python.runFile". 

How do I find out what the commands are called?

**Comment by ryuta46** [comment]
I found this.
https://stackoverflow.com/a/50777155/10981066

In short,

1. Execute "Developer: Set Log Level..." and select "trace" in the command palette.
2. Execute command of you want to know the name.
3. You can see the name in output panel for Window process( you can set the process for output in the rightside of the output panel).

**Comment by ryuta46** [comment]
I added this information to the README file.

https://github.com/ryuta46/vscode-multi-command/blob/master/README.md
