### ISSUE TITLE
Feature Request: workbench.action.closeSideBar to Close Side Bar

### ISSUE THREAD

**Issue by cbejensen** [ryuta46/vscode-multi-command#15]
I was making a [macro](https://github.com/geddski/macros) to close both the side bar and the panel (since I often have Explorer and Terminal open at the same time) so I can quickly focus on code, but it appears there's no command to **close** the side bar. I see `workbench.action.toggleSidebarVisibility` to _toggle_ the side bar, but I'd like my macro to make the side bar and panel be closed, even if one or the other is already closed. Using this command when only the panel is open would cause the side bar to open.

I do see `workbench.action.closePanel` to close the panel, but no such command seems to exist for the side bar. If it exists for the panel, it seems like a good idea to have a corresponding command for the side bar.

**Comment by cbejensen** [comment]
P.S. this is my workaround for now:

```
"macros": {
  "toggleSideBarAndPanel": [
    "workbench.action.focusSideBar", // make sure sidebar is open so toggleSideBar closes it
    "workbench.action.toggleSidebarVisibility",
    "workbench.action.closePanel"
  ]
}
```

**Comment by ryuta46** [comment]
@cbejensen 
This extension combinates _existing commands_ and use it as one command.
So you cannot create a completely new command.

I understand what you want, but it doesn't seem to be supported in this plugin.
It seems to be supported in vscode itself.

Anyway, your workaround also works in this plugin, multi-command.

```json
    "multiCommand.commands": [
        {
            "command": "closeSideBarAndPanel",
            "sequence": [
                "workbench.action.focusSideBar",
                "workbench.action.toggleSidebarVisibility",
                "workbench.action.closePanel"
            ]                
        }
    ],
```

**Comment by cbejensen** [comment]
I am so sorry, I meant to post this on VS Code's repo, not sure how I messed that one up. My bad!
