### ISSUE TITLE
Run external command

### ISSUE THREAD

**Issue by Silverbug** [ryuta46/vscode-multi-command#17]
Hi, 

This might be a really basic thing I've overlooked, but can you call external commands (bash) as part of a sequence? and have them run synchronously ?

Cheers,

Paul

**Comment by ryuta46** [comment]
You can do that by a combination with other extension like command-runner.
https://marketplace.visualstudio.com/items?itemName=edonet.vscode-command-runner

Sample setting is here.
```
    "multiCommand.commands": [
        {
            "command": "multiCommand.runExternalCommand",
            "sequence": [
                {
                    "command": "command-runner.run",
                    "args": { "command": "echo file" }
                }
            ]            
        },
    ],
    "command-runner.commands": {
        "echo file": "echo ${file}"
    }
```
