### ISSUE TITLE
Fail to invoke toggleMaximizedPanel with a shortcut

### ISSUE THREAD

**Issue by wdscxsj** [ryuta46/vscode-multi-command#22]
I used to bind `Alt+X` to `workbench.action.toggleMaximizedPanel` but was quite annoyed when it moved the keyboard focus from panel to editor. Then I turn to multi-command for rescue:

settings.json:

```
"multiCommand.commands": [
    {
        "command": "multiCommand.toggleMaximizedPanel",
        "sequence": [
            "workbench.action.toggleMaximizedPanel",
            "workbench.action.focusPanel",
        ]
    },
]
```

keybindings.json:

```
{
    "key": "alt+x",
    "command": "extension.multiCommand.execute",
    "args": { "command": "multiCommand.toggleMaximizedPanel" },
},
```

Unfortunately this doesn't work on my laptop, even without the `focusPanel` line. Sometimes the panel can be maximized, but it never goes back on a second `Alt+X`. Manually invoking `multiCommand.toggleMaximizedPanel` works flawlessly, but a shortcut will be much better. Any suggestion, please?

**Comment by ryuta46** [comment]
What about defining 2 command sequences and bind them according to the focus location?

settings.json
```
"multiCommand.commands": [
        {
            "command": "multiCommand.toggleMaximizedPanelInEditor",
            "sequence": [
                "workbench.action.toggleMaximizedPanel",
                "workbench.action.focusPanel",
            ]
        },
        {
            "command": "multiCommand.toggleMaximizedPanelInPanel",
            "sequence": [
                "workbench.action.toggleMaximizedPanel",
                "workbench.action.focusLastEditorGroup",
            ]
        }
]
```

keybindings.json
```
    {
        "key": "alt+x",
        "command": "extension.multiCommand.execute",
        "args": { "command": "multiCommand.toggleMaximizedPanelInEditor" },
        "when": "!panelFocus"
    },
    {
        "key": "alt+x",
        "command": "extension.multiCommand.execute",
        "args": { "command": "multiCommand.toggleMaximizedPanelInPanel" },
        "when": "panelFocus"
    }
```

or, you may use `"when": "terminalFocus"` if the panel you want to maximize is terminal.

**Comment by wdscxsj** [comment]
@ryuta46 Thanks for your response! But maybe my previous description was a bit misleading. `workbench.action.toggleMaximizedPanel` already switches the focus between the panel and the editor (as your separate commands do), but I want to keep the focus in the panel. That's why `workbench.action.focusPanel` was specified as the second command.

If you try my configuration, it'll be clear that `Alt+X` doesn't work as expected when the panel is maximized (a potential bug?), but a manual invocation is OK.

**Comment by ryuta46** [comment]
@wdscxsj 
I tried your settings and keybindings again but it seems to work as expected.

![multi-command](https://user-images.githubusercontent.com/18746908/77523998-f8ceb680-6ec9-11ea-8402-d9269640c256.gif)

Is the behavior of the above video different from what you expect? Or will it behave differently in your environment?

My environment is
* macOS 10.15.2
* VSCode 1.42.1
* multi-command 1.4.0

**Comment by wdscxsj** [comment]
@ryuta46 Thank you so much for the video! I'm afraid it does work differently here:

![demo](https://user-images.githubusercontent.com/863369/77528482-02a3ea00-6ec9-11ea-8afa-b4eaad16a481.gif)

My environment:

- Windows 10 64-bit
- VSCode 1.43.2 64-bit
- multi-command 1.4.0

**Comment by ryuta46** [comment]
@wdscxsj 
I reproduced on my Windows PC and I found the solution.

Please see this section in VSCode documents:
https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

I added the following in settings.json to execute multi-command when the focus is in the terminal.
```
    "terminal.integrated.commandsToSkipShell": [
        // Ensure the toggle sidebar visibility keybinding skips the shell
        "extension.multiCommand.execute",
    ]
```

I don't know why the behaviors in Mac and Windows are different, but I think the integrated shell in windows consumes 'alt' hot key so that multi-command couldn't be executed.

**Comment by wdscxsj** [comment]
@ryuta46 This works perfectly. You are my hero! 👍
