### ISSUE TITLE
Offer bash commands possibility in config

### ISSUE THREAD

**Issue by aymericbouzy** [ryuta46/vscode-multi-command#26]
I would like to implement the "checkout to primary git branch and sync" workflow. I think this is a great use case for this extension.

I'm struggling with using `git.checkout` command because it expects arguments, but asks for some of them via user prompt ...

Ultimately, I would simply like to be able to do `git checkout develop` as a bash command.

Would you consider the following config syntax?

```json
    {
      "command": "multiCommand.checkoutDevelop",
      "sequence": [
        { "bash": "git checkout develop" },
		"git.sync"
      ]
    }
```

**Comment by ryuta46** [comment]
How about combining another extension like [Command Runner](https://marketplace.visualstudio.com/items?itemName=edonet.vscode-command-runner)?

You can define your multi command as:
```
        {
            "command": "multiCommand.checkoutDevelop",
            "sequence": [
              { "command": "command-runner.run", "args": {"command": "git checkout develop"} },
              "git.sync"
            ]
        }
```

I think it's a good idea to add bash command execution feature to multi-command extension, but I think it would be more flexible to combine it with an extension specialized for command execution.

**Comment by aymericbouzy** [comment]
Didn't know about that extension! Maybe consider mentioning it in the Readme for people looking to implement workflows like mine?

**Comment by ryuta46** [comment]
Sounds good.
I will add a description of the workflow for cases like this one to README later.
