### ISSUE TITLE
Feature Request: Support specifying commands in keybindings.json

### ISSUE THREAD

**Issue by leighmcculloch** [ryuta46/vscode-multi-command#31]
Support specifying commands in keybindings.json so as to keep all information together rather than split across json files, for simple usages.

Example:
`keybindings.json`
```json
{ 
    "key": "F1", 
    "command": "extension.multiCommand.execute" , 
    "args": { "commands": ["cursorDown", "cursorDown", "cursorDown"] },
    "when": "editorTextFocus"
}
```

That ☝🏻 is instead of:
`keybindings.json`
```json
{ 
    "key": "F1", 
    "command": "extension.multiCommand.execute" , 
    "args": { "command": "multiCommand.down3Lines" },
    "when": "editorTextFocus"
}
```

`settings.json`
```json
"multiCommand.commands": [
    {
        "command": "multiCommand.down3Lines",
        "sequence": [
            "cursorDown",
            "cursorDown",
            "cursorDown"
        ]
    }
]
```

**Comment by ryuta46** [comment]
Very simple and useful feature.
I'll try to implement this feature in next version.

**Comment by ryuta46** [comment]
Implemented in 1.5.0.
Please reopen this issue or create new issue if you have any problem about this feature.
Thanks.

**Comment by leighmcculloch** [comment]
Thank you @ryuta46!

**Comment by leighmcculloch** [comment]
Just tested it, and it works great!
