### ISSUE TITLE
Extension kind is not defined and always runs remotely

### ISSUE THREAD

**Issue by leighmcculloch** [ryuta46/vscode-multi-command#41]
This vscode extension doesn't specify the `extensionKind` field in `package.json` and as such it runs as a `workspace` extension. Workspace extensions will always run remotely when VSCode is using the remote containers/ssh extension and running the VSCode server inside a remote container/instance.

I think it is unnecessary for the extension to only run remotely, or rather, it could run either remotely or locally.

See this article for more details: https://code.visualstudio.com/api/advanced-topics/remote-extensions

To have it run locally or remotely the `extensionKind` property can be added to `package.json` with value `["ui", "workspace"]`.

**Comment by leighmcculloch** [comment]
I forgot to mention, the main side-effect of only running remotely is that when using VSCode and starting a remote container the extension will be disabled until the user manually installs the extension in the container. If the extension is configured to run with either the extension will continue running and the user could choose to install it in the container if they wished.

**Comment by ryuta46** [comment]
I didn't care `extensionKind` field.
I'll check the article you mentioned.
Thank you.

**Comment by ryuta46** [comment]
Thank you for the PR.
I released this change as v1.5.1.
Please reopen this issue if you have any problem about this change.

Thanks.
