### ISSUE TITLE
Command on save

### ISSUE THREAD

**Issue by dustinlacewell** [ryuta46/vscode-multi-command#42]
How to execute a multi-command on save?

**Comment by ryuta46** [comment]
@dustinlacewell This extension itself does not have the feature to execute commands on save.
Please use other extension like [Run command on Save](https://marketplace.visualstudio.com/items?itemName=kirankotari.RunCommandOnSave&ssr=false#overview).

**Comment by dustinlacewell** [comment]
Thanks.
