### ISSUE TITLE
User vs. workspace conflict

### ISSUE THREAD

**Issue by guestieng** [ryuta46/vscode-multi-command#44]
When defining `multiCommand.commands` in "User" as well as(!) in "Workspace" settings (sometimes it's helpful to have this separation for different commands) and (!) when referring to a specific command from User settings in keybindings.json,
it won't be found.
An Example:
```
{ 
        "key": "<some shortcut>", 
        "command": "extension.multiCommand.execute" , 
        "args": { "command": "multiCommand.<some_command_label>" }
}
```
This yould yield the error "command 'multiCommand.<some_command_label>' not found", if `multiCommand.<some_command_label>` was defined in the User settings.
If, however, the `multiCommand.commands` definition was removed from the workspace settings,  `multiCommand.<some_command_label>` would be found!

**Comment by ryuta46** [comment]
@guestieng Did you define commands with object style in settings as below ?

```json
"multiCommand.commands": {
    "multiCommand.down3Lines": {
        "sequence": [
            "cursorDown",
            "cursorDown",
            "cursorDown"
        ]
    }
}
```
If you defined with array style, please try object style to avoid to conflict user's settings and workspace's by reading [this section in README](https://github.com/ryuta46/vscode-multi-command#usage-with-settingsjson).

When you have some troubles  even if you are using object style, please share your settings to check the detail.

**Comment by guestieng** [comment]
Alright, that helped. thank you very much!
