### ISSUE TITLE
[Feature Request] Title

### ISSUE THREAD

**Issue by lonix1** [ryuta46/vscode-multi-command#52]
When editing `keybindings.json` is it possible to add a `"title" : "foo"` as well?

When you open the "Keyboard Shortcuts" view, all multi-commands have the same title "Multi command: Execute multi command". So it's hard to tell them apart.

**Comment by ryuta46** [comment]
I think it's impossible from an extension.
"Keyboard shortcuts" view shows only command names and not show the arguments.
I couldn't find the way to customize the appearance.
Please report the problem to the vscode github to show the command with argument in "Keyboard shortcuts" if you want.
