### ISSUE TITLE
Split and open file?

### ISSUE THREAD

**Issue by joshstobbs** [ryuta46/vscode-multi-command#56]
Hey there!

Thank you for this extension it's really opened up the possibilities of what I think I'm able to orchestrate in VS Code.  I'm facing an issue now though and am looking for some guidance - in theory I'm trying to open up a new split then trigger the quick picker to choose what file goes in that split.

I'm working with these series of commands right now and I'm unsure of where I'm going wrong or if this is possible at all.  I'd really appreciate any guidance!

```
"multiCommand.splitRightOpenFile": {
    "sequence": [
        "workbench.action.newGroupRight",
        "workbench.action.navigateRight",
        "workbench.action.quickOpen"
    ]
}
```

**Comment by ryuta46** [comment]
@joshstobbs 
Please try the sequence as follows

```json
{
    "multiCommand.commands": 
        {
            "multiCommand.splitRightOpenFile": {
                "sequence": [
                    "workbench.action.newGroupRight",
                    "workbench.action.navigateLeft",
                    "workbench.action.navigateRight",
                    "workbench.action.quickOpen"
                ]
            }            
        }
   
}
```

I'm not sure but the focus after `workbench.action.newGroupRight` command was executed is kind of strange(the cursor is blinking in left pane but the close button in the upper right corner of the right pane is also active).

So I added the command `workbench.action.navigateLeft` to get back the focus to the left pane as a try.
The sequence works as expected for me.

**Comment by joshstobbs** [comment]
That is fantastic, thank you for the help!  Really appreciate you taking the time to look into this.
