### ISSUE TITLE
Simplify implementation

### ISSUE THREAD

**Issue by krzkaczor** [ryuta46/vscode-multi-command#7]
I have few suggestions after looking at code:
1. https://github.com/ryuta46/vscode-multi-command/blob/master/src/extension.ts#L48
is there any reason why is this so complicated? Normal for of loop with await inside will result in similiar sequential execution.

2. From what I see `vsc` supports modern JS so transpilation is not required. (await async works natively)

**Comment by ryuta46** [comment]
Thank you for your advise!
I was a newbie of TypeScript when I first wrote this plugin.
I'll check the implementation.
