### ISSUE TITLE
How to display 'resourceFilename, resourceDirname, resourcePath, resource' variables values when saving a file?

### ISSUE THREAD

**Issue by JLLMNCHR** [ryuta46/vscode-multi-command#78]
In VSCODE, using the multi-command extension, I would like to know how I have to configure the keybindings.json, so that when recording (CTRL s) it displays the **value of some variables like**:

**resourceFilename, resourceDirname, resourcePath, resource**

None of the following attempts of declaring "text" line works:

```
[
    {
        "key": "ctrl+s",
        "command": "extension.multiCommand.execute",
        "args": {
            "interval": 1000,
            "sequence": [
                {
                    "command": "workbench.action.files.save"
                },
                {
                    "command": "workbench.action.terminal.sendSequence",
                    "args": {
                        "text": "echo ${resourceDirname} ${resourcePath} ${resourceFilename} ${resource}"
			//"text": "echo `${resourceDirname}` `${resourcePath}` `${resourceFilename}` `${resource}`"
			//"text": "echo resourceDirname resourcePath resourceFilename resource"
                    }
                }
            ]
        }
    }
]
```

**Comment by ryuta46** [comment]
Please read [Advanced Settings in README.md](https://github.com/ryuta46/vscode-multi-command#advanced-settings).

Variable substitution is enabled only when the flag `variableSubstitution` is set true.
You can use `${file}` variable in your command.
Note that all variables in vscode is not supported in multi-command extension.

**Comment by unikitty37** [comment]
@ryuta46  Is it possible to save the current value of a variable and reuse it in a later step? I'm guessing multi-command doesn't have a way of persisting values 

What I want to do is:

* Save the value of `playwright.reuseBrowser`
* Set `playwright.reuseBrowser` to false
* Run "Test: Run Test at Cursor"
* Restore `playwright.reuseBrowser` to the initially-saved value

One way I thought of was to save `playwright.reuseBrowser` to `playwright.ORIG.reuseBrowser`, then delete it afterwards, but I can't find a command to set or delete user settings. Unfortunately "set" returns quite a few search results 😁
