### ISSUE TITLE
Commands don't appear in command palette

### ISSUE THREAD

**Issue by guillochon** [ryuta46/vscode-multi-command#8]
Currently new commands do not appear in the command palette (`ctrl+alt+p`), as there seems to be no way to name a command beyond the internal name. As an example, the command `editor.action.formatDocument` appears as `Format Document` in the command palette, it would be nice if the custom commands also appeared in the palette. Right now the only way to invoke them appears to be through a keybinding.

**Comment by ryuta46** [comment]
Sounds great.
I'll check how to add a command to the command paltette.

**Comment by ryuta46** [comment]
Added functionality in new release, 1.3.0.
Adding command in command palette dynamically is not supported with visual studio code.
So I added custom picker and execute command sequence in some steps.
Please refer README.md.

**Comment by guillochon** [comment]
Thanks, this is useful!
