### ISSUE TITLE
Auto handle input prompt

### ISSUE THREAD

**Issue by huehnerlady** [ryuta46/vscode-multi-command#83]
Hi,

I am trying to implement a multi command where I 
* stash
* pull with rebase
* stash pop

my keybinding.json looks like this:
```json
    {
        "key": "cmd+alt+ctrl+u",
        "label": "Multi-command: git stash, pull rebase, stash pop",
        "command": "extension.multiCommand.execute",
        "args": { 
            "sequence": [
                "git.stashIncludeUntracked",
                "git.pullRebase",
                "git.stashPopLatest"
            ]
        }
    },
```

But when I run it I always get the prompt to add a text:

![image](https://github.com/user-attachments/assets/9bb6b722-a7b9-4b5c-bd94-c7205c96d620)

I would like to also automate that.
How can I do that?

**Comment by ryuta46** [comment]
I checked [the source of "git.stashIncludeUntracked" command](https://github.com/microsoft/vscode/blob/05b68aafc24e443bc1878476cbe89d995d7a61fc/extensions/git/src/commands.ts#L3662-L3666) and found that there is no option to avoid the message prompt for stashing unfortunately.

If you can use git command in your environment, you may use "Command Runner" extension  to do that.
Please also refer [the section about "Command Runner" in README.md](https://github.com/ryuta46/vscode-multi-command?tab=readme-ov-file#using-shell-commands-in-a-command-sequence)
```json
{
        "key": "cmd+alt+ctrl+u",
        "command": "extension.multiCommand.execute",
        "args": { 
            
            "sequence": [
                {
                    "command": "command-runner.run",
                    "args": { "command": "git stash" }
                },
                
            ]
        }
    }
```

**Comment by huehnerlady** [comment]
@ryuta46 thanks for the answer. Unfortunately that command does not seem to work for me.

When I use that I see the terminal opening and the command executing and also the output that it was successful, but the actual file did not get stashed. when I use the same terminal and type the same command I get the same output as I get with the shortcut, but the file also gets stashed.

I also tried with interval, but that doesn't seem to work either. Any idea why?


Here is my command
```
    {
        "key": "cmd+alt+ctrl+u",
        "label": "Multi-command: git stash, pull rebase, stash pop",
        "command": "extension.multiCommand.execute",
        "interval": 10000,
        "args": { 
            "sequence": [
                {
                    "command": "command-runner.run",
                    "args": { "command": "git stash --include-untracked" }
                },
                "git.pullRebase",
                "git.stashPopLatest"
            ]
        }
    }
```

**Comment by ryuta46** [comment]
Please check the stash command is executed as you expected.

* Check you can stash with "git stash" command in VSCode terminal.
* Check you can stash with only "Command Runner" extension.
```json
{
  "key": "cmd+alt+ctrl+u",
  "command": "command-runner.run",
  "args": { "command": "git stash" }
}
```
* Check you can stash with only one command in multi-command sequence.
```json
{
  "key": "cmd+alt+ctrl+u",
  "command": "extension.multiCommand.execute",
  "args": { 
    "sequence": [
      {
        "command": "command-runner.run",
        "args": { "command": "git stash" }
      }
    ]
  }
}
```

And please don't forget to save the target file before executing any stash try.

**Comment by huehnerlady** [comment]
```
{
  "key": "cmd+alt+ctrl+u",
  "command": "command-runner.run",
  "args": { "command": "git stash" }
}
```

works

```
{
  "key": "cmd+alt+ctrl+u",
  "command": "extension.multiCommand.execute",
  "args": { 
    "sequence": [
      {
        "command": "command-runner.run",
        "args": { "command": "git stash" }
      }
    ]
  }
}
```

works

```
    {
        "key": "cmd+alt+ctrl+u",
        "command": "extension.multiCommand.execute",
        "args": { 
            "sequence": [
            {
                "command": "command-runner.run",
                "args": { "command": "git stash" }
            },
                        "git.pullRebase",
                        "git.stashPopLatest"
            ]
        }
    },
```

doesn't work :(

**Comment by huehnerlady** [comment]
any idea what I can do to fix that?

**Comment by ryuta46** [comment]
> doesn't work :(

Please provide details. What did you expect to happen and what were the results?

**Comment by huehnerlady** [comment]
This one seems to work now, so I do everything manually with command-runner

```
    {
        "key": "cmd+alt+ctrl+u",
        "command": "extension.multiCommand.execute",
        "args": { 
            "sequence": [
                {
                    "command": "command-runner.run",
                    "args": { "command": "git stash" }
                },
                {
                    "command": "command-runner.run",
                    "args": { "command": "git fetch --prune" }
                },
                {
                    "command": "command-runner.run",
                    "args": { "command": "git pull --rebase" }
                },
                {
                    "command": "command-runner.run",
                    "args": { "command": "git stash pop" }
                }
            ]
        }
    },
```

**Comment by huehnerlady** [comment]
> > doesn't work :(
> 
> Please provide details. What did you expect to happen and what were the results?

It did not actually stash the items as expected and so when I did the rebase it said I have uncommitted changes and that I need to stash them

**Comment by huehnerlady** [comment]
@ryuta46 thanks for the help, for me the issue would be fixed, unless you want to track something?

**Comment by ryuta46** [comment]
It's fine. I close this issue.
